export const ORDER_DETAILS_DOING = 'ORDER_DETAILS_DOING';
export const ORDER_DETAILS_DONE = 'ORDER_DETAILS_DONE';
export const ORDER_DETAILS_ERROR = 'ORDER_DETAILS_ERROR';

export const ORDER_RECEIVE_DOING = 'ORDER_RECEIVE_DOING';
export const ORDER_RECEIVE_DONE = 'ORDER_RECEIVE_DONE';
export const ORDER_RECEIVE_ERROR = 'ORDER_RECEIVE_ERROR';

export const ORDER_CANCEL_DOING = 'ORDER_CANCEL_DOING';
export const ORDER_CANCEL_DONE = 'ORDER_CANCEL_DONE';
export const ORDER_CANCEL_ERROR = 'ORDER_CANCEL_ERROR';

export const ORDER_COMPLETE_DOING = 'ORDER_COMPLETE_DOING';
export const ORDER_COMPLETE_DONE = 'ORDER_COMPLETE_DONE';
export const ORDER_COMPLETE_ERROR = 'ORDER_COMPLETE_ERROR';